name: dotnet-build

on:
  push:
    branches: [ "main" ]
    
  schedule:
    - cron: '0 * * * *'
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Obter codigo do repositorio
      uses: actions/checkout@v4

    - name: Configurar o ambiente
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restaurar dependências
      run: dotnet restore github4women/github4women.csproj

    - name: Compilar
      run: dotnet build --configuration Release --no-restore